config/routes.rb
Rails.application.routes.draw do
  root "tops#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
 resources :users, only: [:index, :edit, :update] do
    collection do
      patch :update_card
      patch :update_mail
    end
  end

  get 'carts/index' => 'carts#index'
  post 'carts/create' => 'carts#create'
  delete 'carts/destroy' => 'carts#destroy'


  get 'carts/register' => 'carts#register'

  get 'searches/index' => 'searches#index'
  get 'searches/show' => 'searches#show'

  # -- クーポン機能 --------------------
  resources :coupons, only: [:index, :new, :create]

  # -- 検索機能 --------------------
  resources :searches, only: [:index] do
    collection do
      get :result
    end
  end


  resources :carts, only: [:index, :create, :destroy, :show] do
  end
  resources :orders, only: [:index, :new, :create, :show]
  resources :pre_orders, only: [:new, :create]
  # -- ランキング機能 --------------------
  resources :rankings, only: :index

  # -- ショッピング機能 --------------------
  resources :carts, only: [:index, :create, :destroy, :show] do
    collection do
      get :register
    end
  end
  resources :orders, only: [:index, :new, :create, :show]
  resources :pre_orders, only: [:new, :create]
  resources :scrapings, only: [:index] do
    collection do
      get :category
      get :brand
      get :shop
      get :delivery
      get :payment
    end
  end

  # -- お気に入り機能 --------------------
  resources :favorites, only: [:index] do
    collection do
      post :brand_create
      post :shop_create
    end
    member do
      delete :brand_destroy
      delete :shop_destroy
    end
  end

  # -- カテゴリー --------------------
  resources :top_categories, only: [:index, :show] do
    resources :sub_categories, only: [:index, :show]
  end

  concern :categories do
    resources :top_categories, only: [:index, :show] do
      resources :sub_categories, only: [:index, :show]
    end
  end

  # -- Base ------------------------
  resources :tops, only: [:index]
  resources :brands, only: [:index, :show], concerns: :categories
  resources :shops, only: [:index, :show], concerns: :categories do
    resources :items, only: [:show] do
      resources :favorites, only: [:create, :destroy]
    end
  end
  resources :items, only: [:index]

  scope :mens do
    resources :tops, only: [:index]
    resources :brands, only: [:index, :show], concerns: :categories
    resources :shops, only: [:index, :show], concerns: :categories do
      resources :items, only: [:show]
    end
    resources :top_categories, only: [:index, :show] do
      resources :sub_categories, only: [:index, :show]
    end
    resources :rankings, only: :index
    resources :items, only: [:index]
  end

  scope :ladies do
    resources :tops, only: [:index]
    resources :brands, only: [:index, :show], concerns: :categories
    resources :shops, only: [:index, :show], concerns: :categories do
      resources :items, only: [:show]
    end
    resources :top_categories, only: [:index, :show] do
      resources :sub_categories, only: [:index, :show]
    end
    resources :rankings, only: :index
    resources :items, only: [:index]
  end

  scope :kids do
    resources :tops, only: [:index]
    resources :brands, only: [:index, :show], concerns: :categories
    resources :shops, only: [:index, :show], concerns: :categories do
      resources :items, only: [:show]
    end
    resources :top_categories, only: [:index, :show] do
      resources :sub_categories, only: [:index, :show]
    end
    resources :rankings, only: :index
    resources :items, only: [:index]
  end

  # get '*path', controller: 'application', action: 'render_404'

  # application_contorollerのコメントアウトも外す。

end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  include Checked
  include Ranking
  include Search
  include SetCart
  before_action :set_cart

  def index
    items = Item.all
    url = request.path_info
    @items = search_items_by_gender(url, items)

    @newest_items = @items.order("created_at DESC").includes(:images).limit(9)

    # クーポン機能
    if Coupon.exists?
      @coupon = Coupon.first
      @coupon_shops = Coupon.all.includes(:shop).map{|coupon| coupon.shop}
      @coupon_items = @coupon_shops.map{|shop| shop.items}
      @coupon_items = @coupon_items.flatten.slice(0, 9)
    end

    @top_categories = TopCategory.all.includes(:sub_categories)
    @brands = Brand.order("items_count DESC").includes(:items).limit(10)
    @shops = Shop.order("items_count DESC").includes(:items).limit(10)

    if user_signed_in?
      @cart = current_user.cart
      @cart_length = @cart.item_nums.length
      # チェックしたアイテム
      @checked_items = get_checked_items.slice(0, 18)
      # チェックしたショップ
      @checked_shops = get_checked_shops.slice(0, 8)
    end

    @rankings = get_ranking_items.slice(0, 9)
  end

  def men
  end

  def women
  end

  def kid
  end
end

app/views/tops/left/_brand_list.html.haml
%ul#top__left__search__list.clearfix
  - brands.each_with_index do |brand, i|
    - case i
    - when 0
      - color = "first-color"
    - when 1
      - color = "second-color"
    - when 2
      - color = "third-color"
    - else
      - color = "normal-color"
    %li
      .rank-icon{class: color}
        %i.fa.fa-circle.rank-circle
          .rank-num
            = i+1
      - next_path = request.path_info.sub("tops", "") + "brands/#{brand.id}"
      = link_to brand.name, brand_path(brand), class: "list-title link-list"

app/views/tops/left/_category_list.html.haml
- btn_name = "btn_#{top_category.id}"
- if top_category.name == "オールインワン・サロペット"
  - top_category.name = "オールインワン"

%li
  - next_path = request.path_info.sub("tops", "") + "top_categories/#{top_category.id}"
  = link_to top_category.name, next_path, class: "list-title category-btn", id: btn_name
  .angle-icon
    %i.fas.fa-angle-right
  .popup
    .popup.category-popup{id: "popup-#{top_category.id}"}
      .popup__inner
        %ul.popup__inner__list
          - top_category.sub_categories.each do |sub_category|
            %li.hover-link
              = link_to sub_category.name, top_category_sub_category_path(top_category, sub_category), class: "list-title"

app/views/tops/left/_favorite_list.html.haml
%ul#top__left__favorite__list
  %li.category-btn
    = link_to "アイテム", favorites_path, class: "list-title"
  %li.category-btn
    = link_to "ブランド", favorites_path, class: "list-title"
  %li.category-btn
    = link_to "ショップ", favorites_path, class: "list-title"

app/views/tops/left/_search_list.html.haml
%ul#top__left__search__list
  %li
    = link_to "ブランドから探す", brands_path, class: "list-title link-list"
  %li
    = link_to "ショップから探す", shops_path, class: "list-title link-list"
  %li
    = link_to "ランキングから探す", rankings_path, class: "list-title link-list"

app/views/tops/left/_shop_list.html.haml
%ul#top__left__search__list.clearfix
  - shops.each_with_index do |shop, i|
    - case i
    - when 0
      - color = "first-color"
    - when 1
      - color = "second-color"
    - when 2
      - color = "third-color"
    - else
      - color = "normal-color"
    %li
      .rank-icon{class: color}
        %i.fa.fa-circle.rank-circle
          .rank-num
            = i+1
      = link_to shop.name, shop_path(shop), class: "list-title link-list"