config/routes.rb
Rails.application.routes.draw do
  root "tops#index"
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
 resources :users, only: [:index, :edit, :update] do
    collection do
      patch :update_card
      patch :update_mail
    end
  end

  get 'carts/index' => 'carts#index'
  post 'carts/create' => 'carts#create'
  delete 'carts/destroy' => 'carts#destroy'


  get 'carts/register' => 'carts#register'

  get 'searches/index' => 'searches#index'
  get 'searches/show' => 'searches#show'

  # -- クーポン機能 --------------------
  resources :coupons, only: [:index, :new, :create]

  # -- 検索機能 --------------------
  resources :searches, only: [:index] do
    collection do
      get :result
    end
  end


  resources :carts, only: [:index, :create, :destroy, :show] do
  end
  resources :orders, only: [:index, :new, :create, :show]
  resources :pre_orders, only: [:new, :create]
  # -- ランキング機能 --------------------
  resources :rankings, only: :index

  # -- ショッピング機能 --------------------
  resources :carts, only: [:index, :create, :destroy, :show] do
    collection do
      get :register
    end
  end
  resources :orders, only: [:index, :new, :create, :show]
  resources :pre_orders, only: [:new, :create]
  resources :scrapings, only: [:index] do
    collection do
      get :category
      get :brand
      get :shop
      get :delivery
      get :payment
    end
  end

  # -- お気に入り機能 --------------------
  resources :favorites, only: [:index] do
    collection do
      post :brand_create
      post :shop_create
    end
    member do
      delete :brand_destroy
      delete :shop_destroy
    end
  end

  # -- カテゴリー --------------------
  resources :top_categories, only: [:index, :show] do
    resources :sub_categories, only: [:index, :show]
  end

  concern :categories do
    resources :top_categories, only: [:index, :show] do
      resources :sub_categories, only: [:index, :show]
    end
  end

  # -- Base ------------------------
  resources :tops, only: [:index]
  resources :brands, only: [:index, :show], concerns: :categories
  resources :shops, only: [:index, :show], concerns: :categories do
    resources :items, only: [:show] do
      resources :favorites, only: [:create, :destroy]
    end
  end
  resources :items, only: [:index]

  scope :mens do
    resources :tops, only: [:index]
    resources :brands, only: [:index, :show], concerns: :categories
    resources :shops, only: [:index, :show], concerns: :categories do
      resources :items, only: [:show]
    end
    resources :top_categories, only: [:index, :show] do
      resources :sub_categories, only: [:index, :show]
    end
    resources :rankings, only: :index
    resources :items, only: [:index]
  end

  scope :ladies do
    resources :tops, only: [:index]
    resources :brands, only: [:index, :show], concerns: :categories
    resources :shops, only: [:index, :show], concerns: :categories do
      resources :items, only: [:show]
    end
    resources :top_categories, only: [:index, :show] do
      resources :sub_categories, only: [:index, :show]
    end
    resources :rankings, only: :index
    resources :items, only: [:index]
  end

  scope :kids do
    resources :tops, only: [:index]
    resources :brands, only: [:index, :show], concerns: :categories
    resources :shops, only: [:index, :show], concerns: :categories do
      resources :items, only: [:show]
    end
    resources :top_categories, only: [:index, :show] do
      resources :sub_categories, only: [:index, :show]
    end
    resources :rankings, only: :index
    resources :items, only: [:index]
  end

  # get '*path', controller: 'application', action: 'render_404'

  # application_contorollerのコメントアウトも外す。

end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :shoppings
  has_many :items, through: :shoppings
  has_many :item_nums, through: :shoppings
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include Checked
  include SavedCart
  include SetCart
  include SetCoupon
  before_action :set_coupon
  before_action :set_cart, except: :register
  before_action :authenticate_user!

  def index
    @cart = current_user.cart
    @items = @cart.items
    # カートに含まれる同じアイテムをアイテム番号毎にグループ化
    @item_nums = @cart.item_nums.group(:number)
    @count = @item_nums.count
    # カート内の合計金額を算出
    @total_price = get_total_price(@item_nums)
    @cart.update(total_price: @total_price)
    # チェックしたアイテム
    @checked_items = get_checked_items.slice(0, 8)

    # 「以前カートに入れたアイテム」機能
    @past_item_nums = get_past_item_nums
  end

  def create
    Shopping.create(cart_params)

    # 「以前カートに入れたアイテム」機能
    current_user.past_carts.where(item_num_id: params[:item_num_id]).first_or_create.update(updated_at: Time.current)

    redirect_to controller: 'carts', action: 'index'
  end

  def destroy
    if params[:delete] == "delete_all"
      current_user.cart.shoppings.where(item_num_id: params[:item_num_id].to_i).destroy_all
    else
      current_user.cart.shoppings.find_by(item_num_id: params[:item_num_id].to_i).destroy
    end
    redirect_to :controller => 'carts', :action => 'index'
  end

  def register
    Cart.create(user_id: current_user.id, total_price: 0)
    current_user.update(point: 0)
    redirect_to users_path(id: current_user.id), notice: "ユーザー登録をしました。\n基本情報の登録をお願いします。"
  end

  private
  def cart_params
    params.permit(:item_id, :item_num_id).merge(cart_id: current_user.cart.id)
  end

  def get_total_price(item_nums)
    total_price = 0
    item_nums.each do |item_num|
      if item_num.stock.stock > 0
        total_price += item_num.item.price
      end
    end
    return total_price
  end
end

app/views/carts/_cart_item.html.haml
.item-list
  = link_to shop_item_path(item_num.item.shop, item_num.item) do
    = image_tag item_num.item.images[0].url, class: "cart-image"
  .name
    %p
      = item_num.item.shop.name
    %p
      = item_num.item.brand.name
    .price
      = number_to_currency(item_num.item.price, unit: "￥", precision: 0)
    %span 税別
    .other-text
    .other-text
      = "サイズ：" + item_num.stock.size
  .cart-btn
    = link_to "カートに入れる", carts_create_path(@cart)

app/views/carts/index.html.haml
- if Coupon.exists?
  = render partial: "shared/coupon_header", locals: {coupon_price: @coupon.price, shops: @coupon_shops}
= render "shared/header"
.wrapper
  = render 'layouts/notifications'
  .header
    %i.fas.fa-shopping-cart
    %h1
      ショッピングカート
    %img{alt: "広告", src: "http://zozo.jp/_cart/order/img/step_01.gif"}
  .main-content
    .left-content
      .c.items-content.clearfix
        - if @cart.items.length > 0
          - @item_nums.each do |item_num|
            %dl.items.clearfix{id: item_num.number}
              %dt.cart_image_column
                = link_to shop_item_path(item_num.item.shop, item_num.item) do
                  = image_tag item_num.item.images[0].url, class: "cart-image hover-image"
              %dd.cart_info_column
                .name
                  %p
                    = item_num.item.shop.name
                  %p
                    = item_num.item.brand.name
                  %p
                    = item_num.item.name
                  %p
                    カラー：
                    = item_num.stock.color
                  %p
                    サイズ：
                    = item_num.stock.size
                  %p.red-text
                    = "残り#{item_num.stock.stock}点"
              - if item_num.stock.stock > 0
                %dd.cart_price_column
                  .price.red-text
                    = number_to_currency(item_num.item.price, :unit => "￥", :precision => 0)
                %dd.cart_stock_column
                  .number-area
                    .number-box
                      - if @count[item_num.number] > 1
                        .left-btn.btn
                          = link_to "ー", cart_path(@cart, item_id: item_num.item.id, item_num_id: item_num.id), method: :delete
                      .number
                        = @count[item_num.number]
                      - if  item_num.stock.stock - @count[item_num.number] - 1 >= 0
                        .right-btn.btn
                          = link_to "＋", carts_path(@cart, item_id: item_num.item.id, item_num_id: item_num.id), method: :post
                %dd.cart_delete_column
                  .delete-box
                    = link_to "削除", cart_path(@cart, item_num_id: item_num.id, delete: "delete_all"), method: :delete
              - else
                %dd.sold_out_column.item-sold-out
                  %p 完売しました。
                  = link_to "カートから削除する", cart_path(@cart, item_num_id: item_num.id, delete: "delete_all"), method: :delete, class: "hover-link"
          %dl.clearfix
            %dt.cart_total_column.title_column
              %p 商品合計
            %dd.cart_total_column.price_column.red-text
              = number_to_currency(@total_price, unit: "￥", precision: 0)
          .payment
            %b ツケ払いできます。
            お支払いは
            %span
              = (Time.current + 2.month).strftime("%m月%d日")
            でOK
        - else
          %p.nothing_in_cart
            カートに商品は入っていません。
          = link_to "ショッピングを続ける", root_path, class: "continue-btn"
    - if @cart.items.length > 0 && @cart.total_price > 0
      .cart-next
        .form
          = link_to "レジへ進む", new_pre_order_path, class: "cart-btn"
          .postage
            .postage-text
              %i.fas.fa-exclamation-circle
              .text
                %p 送料は一律200円になりました。
          = link_to "ショッピングを続ける", root_path, class: "continue-link"
    - if @past_item_nums
      .cart-in-item
        %h2 以前カートに入れたアイテム
        %ul#top__center__pickup__contents.clearfix
          - @past_item_nums.each do |item_num|
            #top__center__pickup__contents__item
              - if item_num.item.images[0] && item_num.stock.stock > 0
                %li.item.cart-item
                  = render partial: 'tops/item', locals: {item: item_num.item, image_size: "middle", rank_num: 0, coupon: 0}
                  .cart-btn
                    = link_to "カートに入れる", carts_path(@cart, item_id: item_num.item.id, item_num_id: item_num.id), method: :post
    - if @checked_items
      .cart-in-item
        %h2 チェックしたアイテム
        %ul#top__center__pickup__contents.clearfix
          - @checked_items.each do |item|
            #top__center__pickup__contents__item
              - if item.images[0]
                %li.item.cart-item
                  = render partial: 'tops/item', locals: {item: item, image_size: "middle", rank_num: 0, coupon: 0}